First commit for cheching
tnoktkm/LabWorkFourTerm pull request #1
Opened 2021-02-13 18:01 UTC by tnoktkm

I hope, it not bad

2021-02-13 19:29 UTC, JungleTryne requested changes
Очень даже неплохо

2021-02-13 19:29 UTC, JungleTryne commented on main.cpp
> +    Matrix(std::vector<std::vector<double>> &a, std::vector<double> &b) {
Переменные лучше инициализировать так:
```C++
Matrix(const std::vector<std::vector<double>> &a, const std::vector<double> &b) : a(a), b(b) {}
```

Это хорошо по многим причинам, можешь почитать тут:
https://stackoverflow.com/questions/6822422/c-where-to-initialize-variables-in-constructor

P.S. Еще заметь, я передаю по **константной** ссылке, тем самым гарантируя, что при построении класса матриц я изначальные данные мне векторы не поломаю

2021-02-13 19:29 UTC, JungleTryne commented on main.cpp
> +        for (unsigned int i = 0; i < a.size(); ++i) {
Не знаю как тебе, мне лень писать 'unsigned int'. Я пишу 'size_t'

2021-02-13 19:29 UTC, JungleTryne commented on main.cpp
> +        b[b.size()-1] /= a[a.size()-1][a[0].size()-1];
Получить последний элемент вектора: `b.back()`. Соответственно эта строка будет выглядеть так:
`b.back() /= a.back().back()`

2021-02-13 19:29 UTC, JungleTryne commented on main.cpp
> +    std::vector<double> b;
Не уверен, что пользователю матриц нужно иметь доступ к самим векторам. Лучше сделать эти поля private

2021-02-13 19:29 UTC, JungleTryne commented on main.cpp
> +    test.a[test.a.size() - 1][test.a[0].size() - 1] = 1;
test.a.back().back()

2021-02-13 19:46 UTC, tnoktkm commented on main.cpp
> +    std::vector<double> b;
одна из функций в них нуждается, нужно будет сделать протектед

2021-02-14 07:33 UTC, JungleTryne commented on main.cpp
> +    std::vector<double> b;
`protected` -- это про другое. В данном случае, если функция из-вне так то хочет почитать матрицу, то все равно нужно `a` и `b` сделать приватными и написать просто функцию, которая будет тупо их возвращать:

```C++
std::vector<std::vector<double>> getMatrix() const {
    return this->a;
}
```

Таким образом ты защитишь матрицу от изменений из-вне

2021-02-14 10:50 UTC, tnoktkm commented on main.cpp
> +    Matrix(std::vector<std::vector<double>> &a, std::vector<double> &b) {
готово

2021-02-14 14:27 UTC, JungleTryne requested changes
Начинаем еще шлифовать

2021-02-14 14:27 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +    std::vector<std::vector<double>> a;
Чтобы постоянно не писать `std::vector<std::vector<int>>` ты можешь сделать следующее:
```C++
using matrix_t = std::vector<std::vector<double>>
...
matrix_t a;
```

Просто укороченное название, которое поясняет, что вообще тут происходит

Соответсвенно, для колонок:
```C++
using column_t = std::vector<double>
```

2021-02-14 14:27 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +    std::vector<double> b;
Не давай короткие непонятные названия переменным. Так и объяви
```C++
matrix_t matrix_;
column_t column_;
```

Заметь, я использую нижнее подчеркивание для имен _приватных_ переменных

P.S. Надеюсь ты не руками все заменяешь. Посмотри как в CLion автоматически менять названия переменным

2021-02-14 14:27 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +    int getHeadElementColumn(int k) {
Лучше `k` пусть будет `size_t`. Она де-факто является индексом

2021-02-14 14:27 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +    void groundingColumn(int k) {
Аналогично, `size_t k`

2021-02-14 14:27 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +        test.getA()[test.getHeadElementColumn(i)].swap(test.getA()[i]); // swap rows to the surface
Лучше крокодила `test.getHeadElementColumn(i)` вынеси наружу в отдельную переменную, так читаться будет легче

2021-03-07 17:35 UTC, tnoktkm commented on Task 1, matrix/main.cpp
> +        test.getA()[test.getHeadElementColumn(i)].swap(test.getA()[i]); // swap rows to the surface
готово

2021-03-07 18:49 UTC, JungleTryne requested changes
Нужно разобраться теперь с самой архитектурой. Подумай, какие именно методы должен видеть пользователь твоего класса (другой программист). Как именно он будет использоваться. Прочитай про инкапсуляцию и чем она полезна

2021-03-07 18:49 UTC, JungleTryne commented on Task 1, matrix/main.cpp
>          std::cout << std::endl;
На будущее, функция вывода в консоль в классе это что то странное. А что если я захочу ее выводить не в консоль, а в файл? А что если я хочу ее вывести по другому? Оставь это лучше пользователю твоего класса, предоставив соответствующие методы доступа к любому элементу матрицы.

У раз уж на то пошло, то `getMatrix` прям кричит о том, что ты что то вернешь) А ты возвращаешь ничего, поэтому более хорошее имя -- `printMatrix`

2021-03-07 18:49 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +    int getHeadElementColumn(size_t k) {
Ты уверен, что ты хочешь, чтобы этот метод был публичным? Эта функция используется в алгоритме, ее лучше скрыть из "публичного интерфейса", сделай ее приватной

2021-03-07 18:49 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +    column_t b_;
Имена плохие, что такое a, b?

2021-03-07 18:49 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +    matrix_t& geta() {
Воу воу воу, ты возвращает ссылку на элемент `a_`. А в чем смысл тогда делать `a_` приватным?) Опасный метод, ты либо его удали, либо возвращай не ссылку, а просто `matrix_t`, тогда он скопирует у тебя текущую матрицу

2021-03-07 18:49 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +        test.geta()[element].swap(test.geta()[i]); // swap rows to the surface
`test.geta()` можно заменить просто на `test.a_`

2021-03-07 18:49 UTC, JungleTryne commented on Task 1, matrix/main.cpp
> +        test.geta()[element].swap(test.geta()[i]); // swap rows to the surface
И вообще этот метод должен быть методом класса наверно.

2021-03-07 18:49 UTC, JungleTryne commented on Task 1, matrix/main.cpp
>      column_t               b = { 0.424, -0.005,  0.939, -0.589, -0.588, -0.433};
Не надо такие большие отступы))

2021-03-15 19:17 UTC, tnoktkm commented on Task 1, matrix/main.cpp
>          std::cout << std::endl;
готово

2021-03-15 19:19 UTC, tnoktkm commented on Task 1, matrix/main.cpp
> +    int getHeadElementColumn(size_t k) {
готово, сделал еще лучше. Оба вспомогательных метода(функции) сделал красиво приватными, а нужные из вне - публичными.

2021-03-15 19:23 UTC, tnoktkm commented on Task 1, matrix/main.cpp
> +    column_t b_;
поменял, выбрал более менее читабельные для человека(coefs - coefficients)

2021-03-15 19:28 UTC, tnoktkm commented on Task 1, matrix/main.cpp
> +    matrix_t& geta() {
Мдааа...... самая глупая ошибка здесь)))
Круто что ты ее заметил)) хорошо что разобрались)

2021-03-15 19:29 UTC, tnoktkm commented on Task 1, matrix/main.cpp
>      column_t               b = { 0.424, -0.005,  0.939, -0.589, -0.588, -0.433};
при переносе с лабовского пк полетело))

2021-03-15 19:29 UTC, tnoktkm commented on Task 1, matrix/main.cpp
> +        test.geta()[element].swap(test.geta()[i]); // swap rows to the surface
да-да)) тоже так думаю

2021-03-15 19:41 UTC, JungleTryne commented
lgtm

2021-03-15 19:41 UTC, merged